# Test Technique Data Science Ismael FOUDJO

# Projet 1 : Nettoyage de la Base de données

Temps passé : 1h49 min, le temps de téléchargement du fichier de base n'est pas inclu

1. Importation des librairies utiles

In [1]:
import numpy as np
import pandas as pd

2. Chargement du jeu de données "dtf_test"

In [2]:
dtf=pd.read_csv("C:/Users/ismae/Desktop/Projets data Science/Dataset/dtf_test.csv")
# afficher les 05 premières lignes des données 
dtf.head(5)

,Unnamed: 0,date,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
0,0,2020-03-15,1,1176,5,4.1,4.1,100.0,0.45,0.6,132.0,0.00,59.0,0.0,0.0,44.70687,-0.61908,0.3,0.1
1,1,2020-03-15,1,2030,6,9.8,4.5,70.0,3.29,4.4,198.0,0.36,27.0,0.0,0.0,47.27178,-1.65603,9.8,7.8
2,2,2020-03-15,1,3149,4,3.9,3.6,98.0,0.97,1.3,121.0,0.02,52.0,0.0,0.0,44.82995,-0.18713,22.5,NaN
3,3,2020-03-15,1,3153,4,9.2,6.2,82.0,2.77,3.7,182.0,0.21,100.0,0.0,0.0,47.19588,-1.34525,12.1,NaN
4,4,2020-03-15,1,3154,5,9.1,7.5,90.0,1.87,2.5,184.0,0.12,100.0,0.0,0.0,47.09277,-1.04123,8.6,NaN

In [3]:
print("La taille de la BD  est: {}".format(dtf.shape))

La taille de la BD  est: (11773387, 19)

In [4]:
# Statistique descriptive 
dtf.describe()

,Unnamed: 0,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
count,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.177339e+07,1.172616e+07
mean,5.886693e+06,1.249753e+01,1.045076e+04,3.959059e+00,1.460627e+01,8.703802e+00,7.158356e+01,2.316865e+00,3.097654e+00,1.831592e+02,6.486332e-01,5.899088e+01,1.836343e+02,7.592123e-02,4.552976e+01,2.155067e+00,1.478881e+01,1.414610e+01
std,3.398684e+06,6.928014e+00,4.136392e+03,1.305729e+00,7.790627e+00,5.892406e+00,1.987444e+01,1.700836e+00,2.273920e+00,1.012683e+02,7.554195e-01,4.547502e+01,2.652968e+02,5.607737e-01,1.564204e+00,2.601769e+00,8.333854e+00,8.299397e+00
min,0.000000e+00,1.000000e+00,1.176000e+03,1.000000e+00,-1.190000e+01,-4.600000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.765506e+01,-1.670678e+01,-4.000000e+01,-4.000000e+01
25%,2.943346e+06,6.000000e+00,6.637000e+03,4.000000e+00,9.200000e+00,4.800000e+00,5.700000e+01,1.120000e+00,1.500000e+00,9.700000e+01,1.400000e-01,0.000000e+00,0.000000e+00,0.000000e+00,4.416562e+01,-2.262300e-01,9.000000e+00,8.450000e+00
50%,5.886693e+06,1.200000e+01,9.504000e+03,4.000000e+00,1.440000e+01,9.200000e+00,7.500000e+01,2.020000e+00,2.700000e+00,1.900000e+02,3.700000e-01,9.400000e+01,0.000000e+00,0.000000e+00,4.499662e+01,2.081400e+00,1.450000e+01,1.370000e+01
75%,8.830040e+06,1.900000e+01,1.396700e+04,4.000000e+00,1.980000e+01,1.320000e+01,8.900000e+01,3.140000e+00,4.200000e+00,2.660000e+02,8.900000e-01,1.000000e+02,3.248000e+02,0.000000e+00,4.713866e+01,4.794630e+00,2.025000e+01,1.940000e+01
max,1.177339e+07,2.400000e+01,2.444800e+04,1.200000e+01,4.380000e+01,2.790000e+01,1.000000e+02,2.805000e+01,3.750000e+01,3.600000e+02,8.570000e+00,1.000000e+02,1.003900e+03,1.020000e+02,5.786767e+01,1.083905e+01,6.000000e+01,6.000000e+01

3. Élimination des valeurs extrêmes (températures sèche ou humide de précisément +60°C ou -40°C, qui sont en réalité des erreurs de mesure du capteur).

In [5]:
# éliminer les valeurs extremes de temerature 60 
masque1=(dtf['T2M_D_med']== 60) | (dtf["T2M_U_med"]==60)
dtf=dtf[~ masque1]
print("La nouvelle taille de la BD après avoir applique ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir applique ce filtre est: (11754216, 19)

In [6]:
# éliminer les valeurs extremes de temerature -40 
masque_1=(dtf['T2M_D_med']== -40) | (dtf["T2M_U_med"]==-40)
dtf=dtf[~ masque_1]
print("La nouvelle taille de la BD après avoir applique ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir applique ce filtre est: (11754209, 19)

In [7]:
# Vérification des valeurs suprimées 
dtf.describe()

,Unnamed: 0,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
count,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.175421e+07,1.170699e+07
mean,5.885966e+06,1.249761e+01,1.045551e+04,3.957519e+00,1.460521e+01,8.702629e+00,7.158320e+01,2.316526e+00,3.097202e+00,1.831633e+02,6.486002e-01,5.898678e+01,1.836505e+02,7.592319e-02,4.552798e+01,2.158347e+00,1.472385e+01,1.408121e+01
std,3.398861e+06,6.928037e+00,4.137767e+03,1.302259e+00,7.791169e+00,5.893518e+00,1.987589e+01,1.701001e+00,2.274140e+00,1.012701e+02,7.553849e-01,4.547643e+01,2.653129e+02,5.607421e-01,1.563918e+00,2.600319e+00,8.161083e+00,8.125416e+00
min,0.000000e+00,1.000000e+00,1.176000e+03,1.000000e+00,-1.190000e+01,-4.600000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.765506e+01,-1.670678e+01,-3.970000e+01,-3.590000e+01
25%,2.942230e+06,6.000000e+00,6.637000e+03,4.000000e+00,9.200000e+00,4.800000e+00,5.700000e+01,1.120000e+00,1.500000e+00,9.700000e+01,1.400000e-01,0.000000e+00,0.000000e+00,0.000000e+00,4.416538e+01,-2.247600e-01,9.000000e+00,8.450000e+00
50%,5.886606e+06,1.200000e+01,9.512000e+03,4.000000e+00,1.440000e+01,9.200000e+00,7.500000e+01,2.020000e+00,2.700000e+00,1.900000e+02,3.700000e-01,9.400000e+01,0.000000e+00,0.000000e+00,4.499543e+01,2.128120e+00,1.450000e+01,1.370000e+01
75%,8.828862e+06,1.900000e+01,1.396800e+04,4.000000e+00,1.980000e+01,1.320000e+01,8.900000e+01,3.140000e+00,4.200000e+00,2.660000e+02,8.900000e-01,1.000000e+02,3.248200e+02,0.000000e+00,4.713772e+01,4.794720e+00,2.020000e+01,1.940000e+01
max,1.177339e+07,2.400000e+01,2.444800e+04,1.200000e+01,4.380000e+01,2.790000e+01,1.000000e+02,2.805000e+01,3.750000e+01,3.600000e+02,8.570000e+00,1.000000e+02,1.003900e+03,1.020000e+02,5.786767e+01,1.083905e+01,5.950000e+01,5.930000e+01

4. Restriction à la période concernée par le gel (novembre - mai)

In [8]:
print("la date la plus ancienne avant le filtre : {}".format(np.min(dtf['date'])))

la date la plus ancienne avant le filtre : 2020-03-15

In [9]:
print("la date la plus recente avant le filtre {}".format(np.max(dtf['date'])))

la date la plus recente avant le filtre 2023-08-30

In [10]:
# Convertir en format datetime, on peut avoir certains formats en chaine de caractères 
dtf['date']=pd.to_datetime(dtf['date'])

In [11]:
# Restriction de la periode concernée(novembre-mai), la periode de gel
dtf = dtf[(dtf['date'].dt.month >= 11) | (dtf['date'].dt.month <= 5)]

dtf.head(5)

,Unnamed: 0,date,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
0,0,2020-03-15,1,1176,5,4.1,4.1,100.0,0.45,0.6,132.0,0.00,59.0,0.0,0.0,44.70687,-0.61908,0.3,0.1
1,1,2020-03-15,1,2030,6,9.8,4.5,70.0,3.29,4.4,198.0,0.36,27.0,0.0,0.0,47.27178,-1.65603,9.8,7.8
2,2,2020-03-15,1,3149,4,3.9,3.6,98.0,0.97,1.3,121.0,0.02,52.0,0.0,0.0,44.82995,-0.18713,22.5,NaN
3,3,2020-03-15,1,3153,4,9.2,6.2,82.0,2.77,3.7,182.0,0.21,100.0,0.0,0.0,47.19588,-1.34525,12.1,NaN
4,4,2020-03-15,1,3154,5,9.1,7.5,90.0,1.87,2.5,184.0,0.12,100.0,0.0,0.0,47.09277,-1.04123,8.6,NaN

In [12]:
print("La nouvelle taille de la BD après avoir appliqué ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir appliqué ce filtre est: (7067490, 19)

In [13]:
print("la date la plus recente après le filtre {}".format(np.max(dtf['date'])))

la date la plus recente après le filtre 2023-05-31 00:00:00

5. Suppression des données diurnes (SSI > 50 W/m²)

In [14]:
masque2=dtf['SSI']>50
dtf=dtf[~masque2]
print("La nouvelle taille de la BD après avoir applique ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir applique ce filtre est: (4205761, 19)

In [15]:
# vérifications 
dtf.describe()

,Unnamed: 0,date,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
count,4.205761e+06,4205761,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.205761e+06,4.189430e+06
mean,5.737682e+06,2022-06-06 22:05:29.330556416,1.277501e+01,1.040672e+04,4.342313e+00,8.445905e+00,5.144721e+00,8.158149e+01,2.177764e+00,2.911709e+00,1.777559e+02,2.362154e-01,6.464805e+01,1.432901e+00,8.641421e-02,4.555490e+01,2.134879e+00,8.488194e+00,7.992883e+00
min,0.000000e+00,2020-03-15 00:00:00,1.000000e+00,1.176000e+03,1.000000e+00,-1.190000e+01,-4.600000e+01,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.765506e+01,-1.670678e+01,-3.440000e+01,-3.590000e+01
25%,3.109457e+06,2022-01-14 00:00:00,4.000000e+00,6.633000e+03,4.000000e+00,4.800000e+00,1.500000e+00,7.300000e+01,9.700000e-01,1.300000e+00,9.300000e+01,7.000000e-02,1.000000e+00,0.000000e+00,0.000000e+00,4.418017e+01,-2.376200e-01,4.600000e+00,4.100000e+00
50%,4.975904e+06,2022-05-24 00:00:00,1.700000e+01,9.369000e+03,4.000000e+00,8.800000e+00,5.600000e+00,8.600000e+01,1.800000e+00,2.400000e+00,1.810000e+02,1.500000e-01,9.900000e+01,0.000000e+00,0.000000e+00,4.500300e+01,2.128120e+00,8.600000e+00,8.150000e+00
75%,8.693733e+06,2023-02-20 00:00:00,2.100000e+01,1.396000e+04,5.000000e+00,1.200000e+01,8.900000e+00,9.300000e+01,2.990000e+00,4.000000e+00,2.580000e+02,3.200000e-01,1.000000e+02,0.000000e+00,0.000000e+00,4.714258e+01,4.792450e+00,1.205000e+01,1.150000e+01
max,1.069722e+07,2023-05-31 00:00:00,2.400000e+01,2.444800e+04,1.200000e+01,3.410000e+01,2.410000e+01,1.000000e+02,2.199000e+01,2.940000e+01,3.600000e+02,4.750000e+00,1.000000e+02,5.000000e+01,7.610000e+01,5.100133e+01,9.874370e+00,5.440000e+01,4.610000e+01
std,3.263041e+06,NaN,8.596265e+00,4.106867e+03,1.523292e+00,5.213754e+00,5.004226e+00,1.494350e+01,1.757495e+00,2.349621e+00,1.006455e+02,2.574650e-01,4.493996e+01,6.737268e+00,4.993836e-01,1.579249e+00,2.604561e+00,5.722834e+00,5.646145e+00

6. Suppression des données où la température humide est supérieure à la température sèche (T2M_U > T2M_D + 0.5 [marge prenant en compte l’erreur de mesure]) ;

In [16]:
masque3=dtf["T2M_U_med"]>dtf["T2M_D_med"]+0.5
dtf=dtf[~ masque3]
print("La nouvelle taille de la BD après avoir appliqué ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir appliqué ce filtre est: (4096118, 19)

7. Suppression des données éloignées des situations de gel (T2M > 10°C) ;

In [18]:
masque4=dtf['T2M']>10
dtf=dtf[~ masque4]
print("La nouvelle taille de la BD après avoir appliqué ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir appliqué ce filtre est: (2464815, 19)

In [19]:
# verification 
dtf.describe()

,Unnamed: 0,date,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
count,2.464815e+06,2464815,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.464815e+06,2.454656e+06
mean,5.571943e+06,2022-05-29 19:03:36.353601536,1.160169e+01,1.006868e+04,4.621852e+00,5.123604e+00,2.501425e+00,8.446181e+01,2.034432e+00,2.720100e+00,1.718724e+02,1.425095e-01,5.956990e+01,1.165259e+00,6.352566e-02,4.565363e+01,2.367408e+00,5.601985e+00,5.180029e+00
min,0.000000e+00,2020-03-15 00:00:00,1.000000e+00,1.176000e+03,1.000000e+00,-1.190000e+01,-4.600000e+01,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.765506e+01,-1.670678e+01,-1.470000e+01,-3.400000e+01
25%,2.956790e+06,2021-12-19 00:00:00,4.000000e+00,6.627000e+03,4.000000e+00,2.600000e+00,-5.000000e-01,7.700000e+01,8.200000e-01,1.100000e+00,8.100000e+01,4.000000e-02,0.000000e+00,0.000000e+00,0.000000e+00,4.421693e+01,-1.872200e-01,2.400000e+00,1.900000e+00
50%,7.294065e+06,2022-11-03 00:00:00,7.000000e+00,9.007000e+03,5.000000e+00,5.800000e+00,2.800000e+00,8.800000e+01,1.650000e+00,2.200000e+00,1.690000e+02,1.000000e-01,9.800000e+01,0.000000e+00,0.000000e+00,4.503968e+01,2.153200e+00,5.650000e+00,5.100000e+00
75%,8.479460e+06,2023-02-06 00:00:00,2.100000e+01,1.386800e+04,6.000000e+00,8.100000e+00,5.800000e+00,9.500000e+01,2.770000e+00,3.700000e+00,2.590000e+02,2.000000e-01,1.000000e+02,0.000000e+00,0.000000e+00,4.715107e+01,4.821830e+00,8.300000e+00,7.800000e+00
max,1.069630e+07,2023-05-31 00:00:00,2.400000e+01,2.444800e+04,1.200000e+01,1.000000e+01,1.000000e+01,1.000000e+02,2.199000e+01,2.940000e+01,3.600000e+02,1.060000e+00,1.000000e+02,5.000000e+01,2.370000e+01,5.100133e+01,9.874370e+00,3.580000e+01,3.185000e+01
std,3.193950e+06,NaN,8.587047e+00,3.948148e+03,1.713912e+00,3.526111e+00,4.029367e+00,1.313338e+01,1.735148e+00,2.319704e+00,1.049869e+02,1.312794e-01,4.610993e+01,6.082867e+00,3.481265e-01,1.632446e+00,2.597246e+00,4.989035e+00,5.014952e+00

8. Suppression des données où températures atmosphériques et températures sèches sont trop éloignées (|T2M - T2M_D - 1.5| > 3°C) ;

In [20]:
masque5=np.abs(dtf["T2M"]-dtf["T2M_D_med"]-1.5)>3
dtf=dtf[~ masque5]
print("La nouvelle taille de la BD après avoir appliqué ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir appliqué ce filtre est: (1956054, 19)

9. Suppression des données manquantes sur les variables T2M_U_med, T2M_U_min, T2M_U_max

In [21]:
# supression des valeurs manquantes sur T2M_U_med
# identification des valeurs manquantes 
dtf.isnull().sum()

Unnamed: 0         0
date               0
hour               0
station_id         0
nbre_records       0
T2M                0
DEWT2M             0
RH2M               0
WS2M               0
WS10M              0
WD                 0
VPD                0
CLDC               0
SSI                0
PRECIP             0
lat                0
lon                0
T2M_D_med          0
T2M_U_med       1201
dtype: int64

In [22]:
# Comme c'est la seule colonne présentant les valeurs manquantes, il faudra suprimer les lignes avec la fonction "dropna()"
dtf.dropna(inplace=True)
dtf.head(5)

,Unnamed: 0,date,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
0,0,2020-03-15,1,1176,5,4.1,4.1,100.0,0.45,0.6,132.0,0.00,59.0,0.0,0.0,44.70687,-0.61908,0.3,0.1
1,1,2020-03-15,1,2030,6,9.8,4.5,70.0,3.29,4.4,198.0,0.36,27.0,0.0,0.0,47.27178,-1.65603,9.8,7.8
7,7,2020-03-15,1,3324,4,9.8,4.5,70.0,3.29,4.4,198.0,0.36,27.0,0.0,0.0,47.27163,-1.65622,10.4,10.7
8,8,2020-03-15,1,3898,5,9.8,4.5,70.0,3.29,4.4,198.0,0.36,27.0,0.0,0.0,47.27177,-1.65600,9.4,7.5
9,9,2020-03-15,1,3899,6,9.8,4.5,70.0,3.29,4.4,198.0,0.36,27.0,0.0,0.0,47.27172,-1.65615,9.5,7.7

10. Suppression des jours où le capteur émet strictement moins de 50 fois (en théorie entre 96 et 240 mesures par jour) ;

In [24]:
# Le nombre d'enregistrement étant par heure, puisqu'une journée à 24 heures, on peut avoir en moyenne en théorie ( entre 3.91 et 10 par heures) qu'il faut suprimer
masque6=(dtf['nbre_records']<4) 
dtf=dtf[~masque6]
#dtf.head(5)

In [25]:
print("La nouvelle taille de la BD après avoir appliqué ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir appliqué ce filtre est: (1820155, 19)

In [26]:
np.mean(dtf['nbre_records'])

5.255895239691125

11. Suppression des données de capteurs en cours de fabrication, calibration et test (stations situées à moins de 0.05° d’un point basé à Nantes de latitude 47.266 et de longitude -1.561).

In [28]:
masque7= (dtf['WD']<0.05) | (dtf['lat']==47.266) | (dtf['lon']==-1.561)
dtf=dtf[~masque7]
print("La nouvelle taille de la BD après avoir appliqué ce filtre est: {}".format(dtf.shape))

La nouvelle taille de la BD après avoir appliqué ce filtre est: (1753569, 19)

In [29]:
dtf.describe()

,Unnamed: 0,date,hour,station_id,nbre_records,T2M,DEWT2M,RH2M,WS2M,WS10M,WD,VPD,CLDC,SSI,PRECIP,lat,lon,T2M_D_med,T2M_U_med
count,1.753569e+06,1753569,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06,1.753569e+06
mean,5.598927e+06,2022-05-29 08:11:01.068255744,1.120056e+01,1.016852e+04,5.252037e+00,5.234999e+00,2.574460e+00,8.427985e+01,2.059947e+00,2.754214e+00,1.795074e+02,1.449869e-01,6.011038e+01,1.204821e+00,6.665304e-02,4.562104e+01,2.436401e+00,4.352110e+00,3.901612e+00
min,0.000000e+00,2020-03-15 00:00:00,1.000000e+00,1.176000e+03,4.000000e+00,-1.190000e+01,-4.600000e+01,2.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.113933e+01,-4.427380e+00,-1.455000e+01,-1.510000e+01
25%,2.946834e+06,2021-12-18 00:00:00,4.000000e+00,6.633000e+03,5.000000e+00,2.800000e+00,-4.000000e-01,7.700000e+01,8.200000e-01,1.100000e+00,9.100000e+01,5.000000e-02,0.000000e+00,0.000000e+00,0.000000e+00,4.417303e+01,-1.744100e-01,1.800000e+00,1.350000e+00
50%,7.314260e+06,2022-11-04 00:00:00,7.000000e+00,9.018000e+03,5.000000e+00,5.900000e+00,2.900000e+00,8.800000e+01,1.650000e+00,2.200000e+00,1.780000e+02,1.100000e-01,9.800000e+01,0.000000e+00,0.000000e+00,4.501693e+01,2.164330e+00,4.900000e+00,4.400000e+00
75%,8.534685e+06,2023-02-10 00:00:00,2.000000e+01,1.387600e+04,6.000000e+00,8.200000e+00,5.900000e+00,9.500000e+01,2.770000e+00,3.700000e+00,2.630000e+02,2.100000e-01,1.000000e+02,0.000000e+00,0.000000e+00,4.714075e+01,4.805070e+00,7.350000e+00,6.850000e+00
max,1.069611e+07,2023-05-31 00:00:00,2.400000e+01,2.444800e+04,1.200000e+01,1.000000e+01,1.000000e+01,1.000000e+02,2.199000e+01,2.940000e+01,3.600000e+02,1.030000e+00,1.000000e+02,5.000000e+01,2.370000e+01,5.100133e+01,9.853420e+00,1.150000e+01,1.200000e+01
std,3.241588e+06,NaN,8.496406e+00,3.905651e+03,1.071897e+00,3.495019e+00,4.042980e+00,1.330730e+01,1.765146e+00,2.359813e+00,1.016716e+02,1.332979e-01,4.601194e+01,6.159253e+00,3.569144e-01,1.659995e+00,2.530357e+00,3.695661e+00,3.651668e+00

12. Enregistrement de la nouvelle base de données (nettoyée)

In [30]:
# au format csv 
dtf.to_csv('C:/Users/ismae/Desktop/Projets data Science/Dataset/dtf_test_nettoyée.csv', index=False)

In [31]:
# Au format parquet
dtf.to_parquet('C:/Users/ismae/Desktop/Projets data Science/Dataset/dtf_test_nettoyée.parquet', index=False)